var botmanWidget = {
  frameEndpoint: "chat.html",
  introMessage: "Hi,  I am  UMS BOT. To get started, type 'hello'",
  chatServer: "botman.php",
  title: "UMS BOT",
  mainColor: "Black",
  bubbleBackground: "#ff0000",
  aboutText: "Powered by Umeskia Softwares",
  aboutLink: "https://umeskiasoftwares.com",
  bubbleAvatarUrl: "img/bot.png",
  desktopHeight: 500,
  desktopWidth: 370,
  mobileHeight: 400,
  mobileWidth: 300,
  placeholderText: "Type your message here...",
  headerTextColor: "#fff",
  timeTextColor: "green",
  bubbleTextColor: "#fff",
  bubbleFromUserBackground: "#ff0000",
  bubbleFromUserTextColor: "#fff",
  bubbleFromUserBorderColor: "#ff0000",
  bubbleFromUserAvatarUrl: "img/bot.png",
  bubbleFromUserFontWeight: "bold",
  bubbleFromUserBorderRadius: "20px",
  bubbleFromUserBorderWidth: "2px",
  bubbleFromUserBorderStyle: "solid",
  bubbleFromUserBorderLeftWidth: "0px",
  bubbleFromUserBorderRightWidth: "0px",
  bubbleFromUserBorderTopWidth: "0px",
  bubbleFromUserBorderBottomWidth: "0px",
  bubbleFromUserBorderLeftColor: "#ff0000",
  bubbleFromUserBorderRightColor: "#ff0000",
  bubbleFromUserBorderTopColor: "#ff0000",
  bubbleFromUserBorderBottomColor: "#ff0000",
  bubbleFromUserBorderLeftStyle: "solid",
  bubbleFromUserBorderRightStyle: "solid",
  bubbleFromUserBorderTopStyle: "solid",
  bubbleFromUserBorderBottomStyle: "solid",
  bubbleFromUserBorderLeftRadius: "20px",
  bubbleFromUserBorderRightRadius: "20px",
  bubbleFromUserBorderTopRadius: "20px",
  bubbleFromUserBorderBottomRadius: "20px",
};
